repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect secrets with gitleaks
        entry: gitleaks protect --staged --redact
        language: system
        pass_filenames: false
