[edit]
    command = "code"
    args = ["--wait"]

[git]
    autoCommit = true
    autoPush = true
    commitMessageTemplate = "{{ promptString \"commit message:\" }}"

[data]
    email = "vinh@sudovinh.com"
