[edit]
    command = "code"
    args = ["--wait"]

[git]
    autoCommit = true
    autoPush = true
    commitMessageTemplate = "{{ promptString \"conf: update from chezmoi\" }}"

[data]
    email = "vinhn@users.noreply.github.com"
