[edit]
    command = "code"
    args = ["--wait"]

[git]
    autoCommit = true
    autoPush = true
    commitMessageTemplate = "{{ promptString \"commit message:\" }}"

[data]
    email = "sudovinh@users.noreply.github.com"
